version: '2'
services:
    db:
      image: mysql:8
      environment:
        MYSQL_ROOT_PASSWORD: wordpress
        MYSQL_USER: wordpress
        MYSQL_DATABASE: wordpress
      volumes:
        - ./data/db-mysql:/var/lib/mysql
      ports:
        - "3306:3306"
    app:
      build: .
      links:
        - db
      volumes:
        - ./wordpress:/var/www/wordpress
        - ./docker/php.ini:/usr/local/etc/php/php.ini
    nginx:
      image: nginx:1.12
      links:
        - app
      volumes_from:
        - app
      volumes:
        - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:8080"